name: askasound
description: Custom Swing Music Android App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Audio
  just_audio: ^0.9.36
  
  # HTTP & API
  http: ^1.2.0
  dio: ^5.4.0

  # Auto-update
  package_info_plus: ^8.0.0
  open_file: ^3.3.2
  path_provider: ^2.1.2
  
  # State management
  provider: ^6.1.1
  
  # Storage
  shared_preferences: ^2.2.2
  
  # UI
  mobile_scanner: ^5.2.3
  
  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
